# Generated by Django 3.2.8 on 2023-05-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymemb',
            old_name='imagen',
            new_name='image',
        ),
    ]
